Repository UnnecessaryRain/ironway-client, pull requests merged in 2018-04, with the labels that each got.

#13 Add contextual server message
  index.html
  scripts/app.js
  scripts/auth.js
  scripts/client.js
  scripts/display.js
  scripts/server.js
Labels: code base, feature

#14 Registered online frame
  index.html
  scripts/auth.js
  scripts/display.js
Labels: code base

#15 Documentation!
  scripts/app.js
  scripts/auth.js
  scripts/client.js
  scripts/display.js
  scripts/input.js
  scripts/server.js
Labels: code base

#16 Add dummy prompt for username and server IP
  scripts/auth.js
  scripts/server.js
Labels: feature
